name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting a bug!**
        Please provide the following information to help us investigate.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail.
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: "1. Go to...\n2. Click...\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node.js version, OS, browser, etc.
      placeholder: e.g. Node 20.2.0, Firefox 125, Ubuntu 22.04

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Add logs, screenshots, or any other helpful info.
      placeholder: Paste logs, screenshots, or additional context here.
