name: 🐛 Bug Report
description: Report a bug or unexpected behavior in this project
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting a bug!**
        Please complete the form below so we can understand the issue and fix it.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in as much detail as possible.
      placeholder: A clear and concise description of what the bug is.
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the problem?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A description of what you expected instead.
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment Info (optional)
      description: Node.js version, browser, OS, device, etc.
      placeholder: Example: Node 20.2.0, Firefox 125, Ubuntu 22.04

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context or Logs
      description: Add screenshots, logs, or any other useful context here.
      placeholder: Paste logs, stack traces, screenshots, etc.
      required: false
