import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await sql`CREATE TYPE "directory_status_enum" AS ENUM ('added','queued','processing','done','failed','skipped');`.execute(db);
  await sql`CREATE TYPE "relation_type_enum" AS ENUM ('parent','child','sibling','spouse','grandparent','grandchild','uncle','aunt','nephew','niece','cousin','parent_in_law','child_in_law','sibling_in_law','friend','best_friend','acquaintance','friend_of_friend','colleague','supervisor','subordinate','business_partner','coauthor','classmate','teacher','student','teammate','neighbor','roommate','mentor','mentee');`.execute(db);
  await sql`CREATE TYPE "asset_person_type_enum" AS ENUM ('main','owner','tagged','edge','coauthor','mentions');`.execute(db);
  await sql`CREATE TABLE "asset_person" ("assetId" uuid NOT NULL, "personId" uuid NOT NULL, "type" asset_person_type_enum NOT NULL DEFAULT 'tagged');`.execute(db);
  await sql`CREATE TABLE "web_scrapped_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "longitude" double precision, "latitude" double precision, "countryCode" character varying, "platform" character varying, "platformLocationId" character varying, "platformUrl" character varying);`.execute(db);
  await sql`CREATE TABLE "asset_web_location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assetId" uuid NOT NULL, "webScrappedLocationId" uuid NOT NULL);`.execute(db);
  await sql`CREATE TABLE "directory_job_status" ("directoryId" uuid NOT NULL, "assetsSyncedAt" timestamp with time zone, "processedMetadataDataAt" timestamp with time zone, "createdPersonDataAt" timestamp with time zone);`.execute(db);
  await sql`CREATE TABLE "directory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerId" uuid NOT NULL, "libraryId" uuid, "status" directory_status_enum NOT NULL DEFAULT 'added', "path" character varying NOT NULL, "createdAt" timestamp with time zone NOT NULL DEFAULT now(), "updatedAt" timestamp with time zone NOT NULL DEFAULT now(), "deletedAt" timestamp with time zone, "isOffline" boolean NOT NULL DEFAULT false, "isHidden" boolean NOT NULL DEFAULT false, "albumId" uuid, "parentId" uuid);`.execute(db);
  await sql`CREATE TABLE "person_relationship" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "personId" uuid NOT NULL, "relatedPersonId" uuid NOT NULL, "type" relation_type_enum NOT NULL DEFAULT 'friend', "createdAt" timestamp with time zone NOT NULL DEFAULT now());`.execute(db);
  await sql`CREATE TABLE "person_sidecar" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "personId" uuid NOT NULL, "sidecarPath" character varying NOT NULL, "lastProcessedAt" timestamp with time zone, "updatedAt" timestamp with time zone, "ownerId" uuid NOT NULL);`.execute(db);
  await sql`CREATE TABLE "sites_url" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "createdAt" timestamp with time zone NOT NULL DEFAULT now(), "visitedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP, "preference" integer DEFAULT 0, "description" character varying, "ownerId" uuid NOT NULL);`.execute(db);
  await sql`CREATE TABLE "social_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "personId" uuid, "ownerId" uuid NOT NULL, "platform" character varying, "platformUserId" character varying, "platformUserIdHash" character varying, "thumbnailPath" character varying, "name" character varying, "description" character varying, "url" character varying, "followers" integer, "following" integer, "posts" integer, "updatedAt" timestamp with time zone NOT NULL DEFAULT now(), "lastDownloaded" timestamp with time zone, "lastDownloadedNode" character varying);`.execute(db);
  await sql`CREATE TABLE "web_scrapped_locations_tmp" ("assetId" uuid NOT NULL, "webScrappedLocationId" uuid NOT NULL);`.execute(db);
  await sql`ALTER TABLE "assets" ADD "viewed" boolean NOT NULL DEFAULT false;`.execute(db);
  await sql`ALTER TABLE "albums" ADD "viewed" boolean NOT NULL DEFAULT false;`.execute(db);
  await sql`ALTER TABLE "albums" ADD "parentId" uuid;`.execute(db);
  await sql`ALTER TABLE "person" ADD "height" integer;`.execute(db);
  await sql`ALTER TABLE "person" ADD "age" integer;`.execute(db);
  await sql`ALTER TABLE "person" ADD "country" character varying DEFAULT '';`.execute(db);
  await sql`ALTER TABLE "person" ADD "city" character varying DEFAULT '';`.execute(db);
  await sql`ALTER TABLE "person" ADD "description" character varying DEFAULT '';`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations" ADD CONSTRAINT "PK_f108aed86db5f0796f8cf4963cb" PRIMARY KEY ("id");`.execute(db);
  await sql`ALTER TABLE "asset_web_location" ADD CONSTRAINT "PK_d3d0113232eb2f76265db8a93aa" PRIMARY KEY ("id", "assetId", "webScrappedLocationId");`.execute(db);
  await sql`ALTER TABLE "directory_job_status" ADD CONSTRAINT "PK_370a2344994af13439a0d281d5f" PRIMARY KEY ("directoryId");`.execute(db);
  await sql`ALTER TABLE "directory" ADD CONSTRAINT "PK_3031979b800d63fadf8ce7e33b0" PRIMARY KEY ("id");`.execute(db);
  await sql`ALTER TABLE "person_relationship" ADD CONSTRAINT "PK_2aab9eb70a2910a488996d8f491" PRIMARY KEY ("id", "personId", "relatedPersonId");`.execute(db);
  await sql`ALTER TABLE "person_sidecar" ADD CONSTRAINT "PK_b46f2036c700b669eacbf759e52" PRIMARY KEY ("id", "personId");`.execute(db);
  await sql`ALTER TABLE "sites_url" ADD CONSTRAINT "PK_41f48696ef155779a17af56f322" PRIMARY KEY ("id");`.execute(db);
  await sql`ALTER TABLE "social_media" ADD CONSTRAINT "PK_54ac0fd97432069e7c9ab567f8b" PRIMARY KEY ("id");`.execute(db);
  await sql`ALTER TABLE "albums" ADD CONSTRAINT "FK_cb5b570995108d61679b91949d2" FOREIGN KEY ("parentId") REFERENCES "albums" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "asset_person" ADD CONSTRAINT "FK_dc32756aa43d29d06ee9e5ea1f4" FOREIGN KEY ("assetId") REFERENCES "assets" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "asset_person" ADD CONSTRAINT "FK_0ec8eea50792a8edac463e0f4d9" FOREIGN KEY ("personId") REFERENCES "person" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "asset_web_location" ADD CONSTRAINT "FK_27b097269e805e233a38ff5840b" FOREIGN KEY ("assetId") REFERENCES "assets" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "asset_web_location" ADD CONSTRAINT "FK_cb5a07f71d38b61448c022f7bce" FOREIGN KEY ("webScrappedLocationId") REFERENCES "web_scrapped_locations" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "directory_job_status" ADD CONSTRAINT "FK_370a2344994af13439a0d281d5f" FOREIGN KEY ("directoryId") REFERENCES "assets" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "directory" ADD CONSTRAINT "FK_a360c4f928058736a36d78ec3f1" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "directory" ADD CONSTRAINT "FK_d331c42e7fb3431d302f92bf4d2" FOREIGN KEY ("libraryId") REFERENCES "libraries" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "directory" ADD CONSTRAINT "FK_e6ca8897be660f99da7f696a1ca" FOREIGN KEY ("albumId") REFERENCES "albums" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "directory" ADD CONSTRAINT "FK_93f840b7f321ef230e5645b1012" FOREIGN KEY ("parentId") REFERENCES "directory" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "person_relationship" ADD CONSTRAINT "FK_dc068c837b60c4a54a621f939c9" FOREIGN KEY ("personId") REFERENCES "person" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "person_relationship" ADD CONSTRAINT "FK_af08e3a769ce0e259eca3797357" FOREIGN KEY ("relatedPersonId") REFERENCES "person" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "person_sidecar" ADD CONSTRAINT "FK_5a23c796c10d625785d1a44dc17" FOREIGN KEY ("personId") REFERENCES "person" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "person_sidecar" ADD CONSTRAINT "FK_e4afcfa0ddcd71e527d279d0776" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "sites_url" ADD CONSTRAINT "FK_f89cfb3cbf4ab7b4ae67a66db7d" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "social_media" ADD CONSTRAINT "FK_aaf27905995c991ed4833a82f6c" FOREIGN KEY ("personId") REFERENCES "person" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "social_media" ADD CONSTRAINT "FK_ed8fc731df389b838057c2af6b8" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON UPDATE CASCADE ON DELETE SET NULL;`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations_tmp" ADD CONSTRAINT "FK_8b5bf0e9e3a0e2d305462a58004" FOREIGN KEY ("assetId") REFERENCES "assets" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations_tmp" ADD CONSTRAINT "FK_d201ad3e1acbcefd4931f8ef706" FOREIGN KEY ("webScrappedLocationId") REFERENCES "web_scrapped_locations" ("id") ON UPDATE CASCADE ON DELETE CASCADE;`.execute(db);
  await sql`CREATE INDEX "IDX_cb5b570995108d61679b91949d" ON "albums" ("parentId")`.execute(db);
  await sql`CREATE INDEX "IDX_107725204522ca8d7c65dfdbb0" ON "asset_person" ("personId", "assetId")`.execute(db);
  await sql`CREATE INDEX "IDX_asset_person_assetId_personId" ON "asset_person" ("assetId", "personId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "PK_asset_person" ON "asset_person" ("assetId", "personId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "UQ_web_scrapped_locations_libraryId_path" ON "web_scrapped_locations" ("platform", "platformLocationId")`.execute(db);
  await sql`CREATE INDEX "IDX_27b097269e805e233a38ff5840" ON "asset_web_location" ("assetId")`.execute(db);
  await sql`CREATE INDEX "IDX_cb5a07f71d38b61448c022f7bc" ON "asset_web_location" ("webScrappedLocationId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "UQ_directories_library_path" ON "directory" ("libraryId", "path")`.execute(db);
  await sql`CREATE INDEX "IDX_a360c4f928058736a36d78ec3f" ON "directory" ("ownerId")`.execute(db);
  await sql`CREATE INDEX "IDX_d331c42e7fb3431d302f92bf4d" ON "directory" ("libraryId")`.execute(db);
  await sql`CREATE INDEX "IDX_01a22769542196b4bdb1c69401" ON "directory" ("path")`.execute(db);
  await sql`CREATE INDEX "IDX_e6ca8897be660f99da7f696a1c" ON "directory" ("albumId")`.execute(db);
  await sql`CREATE INDEX "IDX_93f840b7f321ef230e5645b101" ON "directory" ("parentId")`.execute(db);
  await sql`CREATE INDEX "IDX_dc068c837b60c4a54a621f939c" ON "person_relationship" ("personId")`.execute(db);
  await sql`CREATE INDEX "IDX_af08e3a769ce0e259eca379735" ON "person_relationship" ("relatedPersonId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "UQ_person_sidecar" ON "person_sidecar" ("personId", "sidecarPath", "ownerId")`.execute(db);
  await sql`CREATE INDEX "IDX_5a23c796c10d625785d1a44dc1" ON "person_sidecar" ("personId")`.execute(db);
  await sql`CREATE INDEX "IDX_e4afcfa0ddcd71e527d279d077" ON "person_sidecar" ("ownerId")`.execute(db);
  await sql`CREATE INDEX "IDX_f89cfb3cbf4ab7b4ae67a66db7" ON "sites_url" ("ownerId")`.execute(db);
  await sql`CREATE UNIQUE INDEX "UQ_social_media_platform_platformUserId_platformUserIdHash" ON "social_media" ("platform", "platformUserId", "platformUserIdHash")`.execute(db);
  await sql`CREATE INDEX "IDX_aaf27905995c991ed4833a82f6" ON "social_media" ("personId")`.execute(db);
  await sql`CREATE INDEX "IDX_ed8fc731df389b838057c2af6b" ON "social_media" ("ownerId")`.execute(db);
  await sql`CREATE INDEX "IDX_8b5bf0e9e3a0e2d305462a5800" ON "web_scrapped_locations_tmp" ("assetId")`.execute(db);
  await sql`CREATE INDEX "IDX_d201ad3e1acbcefd4931f8ef70" ON "web_scrapped_locations_tmp" ("webScrappedLocationId")`.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`DROP INDEX "IDX_cb5b570995108d61679b91949d";`.execute(db);
  await sql`DROP INDEX "IDX_107725204522ca8d7c65dfdbb0";`.execute(db);
  await sql`DROP INDEX "IDX_asset_person_assetId_personId";`.execute(db);
  await sql`DROP INDEX "PK_asset_person";`.execute(db);
  await sql`DROP INDEX "UQ_web_scrapped_locations_libraryId_path";`.execute(db);
  await sql`DROP INDEX "IDX_27b097269e805e233a38ff5840";`.execute(db);
  await sql`DROP INDEX "IDX_cb5a07f71d38b61448c022f7bc";`.execute(db);
  await sql`DROP INDEX "UQ_directories_library_path";`.execute(db);
  await sql`DROP INDEX "IDX_a360c4f928058736a36d78ec3f";`.execute(db);
  await sql`DROP INDEX "IDX_d331c42e7fb3431d302f92bf4d";`.execute(db);
  await sql`DROP INDEX "IDX_01a22769542196b4bdb1c69401";`.execute(db);
  await sql`DROP INDEX "IDX_e6ca8897be660f99da7f696a1c";`.execute(db);
  await sql`DROP INDEX "IDX_93f840b7f321ef230e5645b101";`.execute(db);
  await sql`DROP INDEX "IDX_dc068c837b60c4a54a621f939c";`.execute(db);
  await sql`DROP INDEX "IDX_af08e3a769ce0e259eca379735";`.execute(db);
  await sql`DROP INDEX "UQ_person_sidecar";`.execute(db);
  await sql`DROP INDEX "IDX_5a23c796c10d625785d1a44dc1";`.execute(db);
  await sql`DROP INDEX "IDX_e4afcfa0ddcd71e527d279d077";`.execute(db);
  await sql`DROP INDEX "IDX_f89cfb3cbf4ab7b4ae67a66db7";`.execute(db);
  await sql`DROP INDEX "UQ_social_media_platform_platformUserId_platformUserIdHash";`.execute(db);
  await sql`DROP INDEX "IDX_aaf27905995c991ed4833a82f6";`.execute(db);
  await sql`DROP INDEX "IDX_ed8fc731df389b838057c2af6b";`.execute(db);
  await sql`DROP INDEX "IDX_8b5bf0e9e3a0e2d305462a5800";`.execute(db);
  await sql`DROP INDEX "IDX_d201ad3e1acbcefd4931f8ef70";`.execute(db);
  await sql`ALTER TABLE "albums" DROP CONSTRAINT "FK_cb5b570995108d61679b91949d2";`.execute(db);
  await sql`ALTER TABLE "asset_person" DROP CONSTRAINT "FK_dc32756aa43d29d06ee9e5ea1f4";`.execute(db);
  await sql`ALTER TABLE "asset_person" DROP CONSTRAINT "FK_0ec8eea50792a8edac463e0f4d9";`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations" DROP CONSTRAINT "PK_f108aed86db5f0796f8cf4963cb";`.execute(db);
  await sql`ALTER TABLE "asset_web_location" DROP CONSTRAINT "PK_d3d0113232eb2f76265db8a93aa";`.execute(db);
  await sql`ALTER TABLE "asset_web_location" DROP CONSTRAINT "FK_27b097269e805e233a38ff5840b";`.execute(db);
  await sql`ALTER TABLE "asset_web_location" DROP CONSTRAINT "FK_cb5a07f71d38b61448c022f7bce";`.execute(db);
  await sql`ALTER TABLE "directory_job_status" DROP CONSTRAINT "PK_370a2344994af13439a0d281d5f";`.execute(db);
  await sql`ALTER TABLE "directory_job_status" DROP CONSTRAINT "FK_370a2344994af13439a0d281d5f";`.execute(db);
  await sql`ALTER TABLE "directory" DROP CONSTRAINT "PK_3031979b800d63fadf8ce7e33b0";`.execute(db);
  await sql`ALTER TABLE "directory" DROP CONSTRAINT "FK_a360c4f928058736a36d78ec3f1";`.execute(db);
  await sql`ALTER TABLE "directory" DROP CONSTRAINT "FK_d331c42e7fb3431d302f92bf4d2";`.execute(db);
  await sql`ALTER TABLE "directory" DROP CONSTRAINT "FK_e6ca8897be660f99da7f696a1ca";`.execute(db);
  await sql`ALTER TABLE "directory" DROP CONSTRAINT "FK_93f840b7f321ef230e5645b1012";`.execute(db);
  await sql`ALTER TABLE "person_relationship" DROP CONSTRAINT "PK_2aab9eb70a2910a488996d8f491";`.execute(db);
  await sql`ALTER TABLE "person_relationship" DROP CONSTRAINT "FK_dc068c837b60c4a54a621f939c9";`.execute(db);
  await sql`ALTER TABLE "person_relationship" DROP CONSTRAINT "FK_af08e3a769ce0e259eca3797357";`.execute(db);
  await sql`ALTER TABLE "person_sidecar" DROP CONSTRAINT "PK_b46f2036c700b669eacbf759e52";`.execute(db);
  await sql`ALTER TABLE "person_sidecar" DROP CONSTRAINT "FK_5a23c796c10d625785d1a44dc17";`.execute(db);
  await sql`ALTER TABLE "person_sidecar" DROP CONSTRAINT "FK_e4afcfa0ddcd71e527d279d0776";`.execute(db);
  await sql`ALTER TABLE "sites_url" DROP CONSTRAINT "PK_41f48696ef155779a17af56f322";`.execute(db);
  await sql`ALTER TABLE "sites_url" DROP CONSTRAINT "FK_f89cfb3cbf4ab7b4ae67a66db7d";`.execute(db);
  await sql`ALTER TABLE "social_media" DROP CONSTRAINT "PK_54ac0fd97432069e7c9ab567f8b";`.execute(db);
  await sql`ALTER TABLE "social_media" DROP CONSTRAINT "FK_aaf27905995c991ed4833a82f6c";`.execute(db);
  await sql`ALTER TABLE "social_media" DROP CONSTRAINT "FK_ed8fc731df389b838057c2af6b8";`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations_tmp" DROP CONSTRAINT "FK_8b5bf0e9e3a0e2d305462a58004";`.execute(db);
  await sql`ALTER TABLE "web_scrapped_locations_tmp" DROP CONSTRAINT "FK_d201ad3e1acbcefd4931f8ef706";`.execute(db);
  await sql`ALTER TABLE "albums" DROP COLUMN "viewed";`.execute(db);
  await sql`ALTER TABLE "albums" DROP COLUMN "parentId";`.execute(db);
  await sql`ALTER TABLE "person" DROP COLUMN "height";`.execute(db);
  await sql`ALTER TABLE "person" DROP COLUMN "age";`.execute(db);
  await sql`ALTER TABLE "person" DROP COLUMN "country";`.execute(db);
  await sql`ALTER TABLE "person" DROP COLUMN "city";`.execute(db);
  await sql`ALTER TABLE "person" DROP COLUMN "description";`.execute(db);
  await sql`ALTER TABLE "assets" DROP COLUMN "viewed";`.execute(db);
  await sql`DROP TABLE "asset_person";`.execute(db);
  await sql`DROP TABLE "web_scrapped_locations";`.execute(db);
  await sql`DROP TABLE "asset_web_location";`.execute(db);
  await sql`DROP TABLE "directory_job_status";`.execute(db);
  await sql`DROP TABLE "directory";`.execute(db);
  await sql`DROP TABLE "person_relationship";`.execute(db);
  await sql`DROP TABLE "person_sidecar";`.execute(db);
  await sql`DROP TABLE "sites_url";`.execute(db);
  await sql`DROP TABLE "social_media";`.execute(db);
  await sql`DROP TABLE "web_scrapped_locations_tmp";`.execute(db);
  await sql`DROP TYPE "directory_status_enum";`.execute(db);
  await sql`DROP TYPE "relation_type_enum";`.execute(db);
  await sql`DROP TYPE "asset_person_type_enum";`.execute(db);
}
